# version: '3.8'
services:
  dev-db:
    image: mongo:latest
    restart: always
    ports:
      - 8080:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: nest-manguito
    # volumes:
    #   - mongodb_data_container:/data/db
    networks:
      - manguito-api
  test-db:
    image: mongo:latest
    ports:
      - 8080:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: nest-manguito
    # volumes:
    #   - mongodb_data_container:/data/db
    networks:
      - manguito-api
networks:
  manguito-api:
    driver: bridge
